events {}

http {
    upstream apps {
        server yellow-app:80;
        server red-app:80;
        server green-app:80;
    }

    server {
        listen 3000;
        location / {
            proxy_pass http://apps;
        }
    }
}
